/*
 Copyright 2017 RockAuto, LLC 
*/
function ResizePiclookup(){var a=0,b=0;"number"==typeof window.innerHeight?(a=window.innerWidth,b=window.innerHeight):document.documentElement&&document.documentElement.clientWidth?(a=document.documentElement.clientWidth,b=document.documentElement.clientHeight):document.body&&document.body.clientWidth&&(a=document.body.clientWidth,b=document.body.clientHeight);if(0<a&&0<b){var a=Math.floor(.66*a),b=Math.floor(.66*b),c=document.getElementById("piclookup");c&&(c.style.maxWidth=a,c.style.maxHeight=b)}}
var outOfLens=!1,outOfImage=!1,last_group_index=null;function MouseOutOfImage(a,b){null==a&&(a=last_group_index);last_group_index=a;outOfImage=!0;outOfLens&&outOfImage&&HideZoomLens(a,b)}function MouseOutOfLens(a,b){null==a&&(a=last_group_index);last_group_index=a;(outOfLens=!0,outOfImage)&&HideZoomLens(a,b)}function MouseOverImage(a,b){null==a&&(a=last_group_index);last_group_index=a;IsCurrentImageZoomable(a)&&(outOfImage=!1,ShowZoomLens(a,b))}
function MouseOverLens(a,b){null==a&&(a=last_group_index);last_group_index=a;IsCurrentImageZoomable(a)&&(outOfLens=!1,ShowZoomLens(a,b))}function ShowZoomLens(a,b){var c=document.getElementById("zoomlens");if(c){var d=document.getElementById("zoomedimage");c.style.display="";d.style.display=""}}function HideZoomLens(a,b){var c=document.getElementById("zoomlens");if(c){var d=document.getElementById("zoomedimage");c.style.display="none";d.style.display="none"}}
function MouseMoveZoom(a,b){if(window.attachEvent&&!window.addEventListener)HideZoomLens(a,b);else if(b.stopPropagation(),null==a&&(a=last_group_index),last_group_index=a,IsCurrentImageZoomable(a)){var c=cataloglite.Listing_GetNodeImageData(a),d=document.getElementById("zoomlens");if(d){var f;document.getElementById("Screen");f=RA.ById("inlineimg["+a+"]");var l=f.getBoundingClientRect(),q=document.getElementById("zoomedimage");if(b){var e=null;"Single"==c.Slots[c.SlotIndex].Type?e=c.Slots[c.SlotIndex].ImageData:
"360"==c.Slots[c.SlotIndex].Type&&(e=c.Slots[c.SlotIndex].List[c.Slots[c.SlotIndex].Index].ImageData);var c=e.Full,m=e.FullDim.Height/e.FullDim.BoxHeight,n=e.FullDim.Width/e.FullDim.BoxWidth;if(IsCurrentImageZoomable(a)){var g=e=null,h=null,m=Math.max(m,n);1.5>m&&(e=2,h=g=200);1.5<=m&&2>m&&(e=3,h=g=150);2<=m&&(e=4,h=g=100);if(f.height<g||f.width<h)g=h=m=Math.min(f.height,f.width)-5;d.style.width=h+"px";d.style.height=g+"px";var m=(window.pageXOffset||document.documentElement.scrollLeft)-(document.documentElement.clientLeft||
0)||document.documentElement&&document.documentElement.scrollLeft||document.body.scrollLeft,g=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0)||document.documentElement&&document.documentElement.scrollTop||document.body.scrollTop,k=b.clientX-d.width/2,n=b.clientY-d.height/2;k<l.left&&(k=l.left);k+d.width>l.right&&(k=l.right-d.width);n<l.top&&(n=l.top);n+d.height>l.bottom&&(n=l.bottom-d.height);n+=g;k+=m;"absolute"!=d.style.position&&(d.style.position=
"absolute");d.style.left!=k+"px"&&(d.style.left=k+"px");d.style.top!=n+"px"&&(d.style.top=n+"px");h=f.width/f.height;m=(k+d.width/2-l.left-m-d.width/2)/f.width;l=(n+d.height/2-l.top-g-d.height/2)/f.height;g=d.width*e;e*=d.height;0!=d.width&&(q.width=g,q.height=e,n=g/d.width,d=e/d.height,f=f.width,h=f/h,f*=n,h*=d,q.style.background="url('"+c+"') no-repeat",q.style.backgroundSize=f+"px "+h+"px",q.style.backgroundPosition="-"+f*m+"px -"+h*l+"px",q.width=g,q.height=e)}else HideZoomLens(a,b)}}}else HideZoomLens(a,
b)}
function IsCurrentImageZoomable(a){null==a&&(a=last_group_index);last_group_index=a;var b=cataloglite.Listing_GetNodeImageData(a);a={};if(!RA.IsEmpty(b)){if("Single"==b.Slots[b.SlotIndex].Type){if(!("FullDim"in b.Slots[b.SlotIndex].ImageData)||0==b.Slots[b.SlotIndex].ImageData.FullDim.Width){a=b.Slots[b.SlotIndex].ImageData;var c=new Image;c.src=a.Full;a.FullDim={};a.FullDim.Width=c.width;a.FullDim.Height=c.height;a.FullDim.BoxWidth=500;a.FullDim.BoxWidth>a.FullDim.Width&&(a.FullDim.BoxWidth=a.FullDim.Width);a.FullDim.BoxHeight=
a.FullDim.Height/a.FullDim.Width*a.FullDim.BoxWidth;500<a.FullDim.BoxHeight&&(a.FullDim.BoxHeight=500,a.FullDim.BoxWidth=a.FullDim.BoxHeight/(a.FullDim.Height/a.FullDim.Width));b.Slots[b.SlotIndex].ImageData=a}a=b.Slots[b.SlotIndex].ImageData}else"360"==b.Slots[b.SlotIndex].Type&&("FullDim"in b.Slots[b.SlotIndex].List[b.Slots[b.SlotIndex].Index].ImageData&&0!=b.Slots[b.SlotIndex].List[b.Slots[b.SlotIndex].Index].ImageData.FullDim.Width||(a=b.Slots[b.SlotIndex].List[b.Slots[b.SlotIndex].Index].ImageData,
c=new Image,c.src=a.Full,a.FullDim={},a.FullDim.Width=c.width,a.FullDim.Height=c.height,a.FullDim.BoxWidth=500,a.FullDim.BoxWidth>a.FullDim.Width&&(a.FullDim.BoxWidth=a.FullDim.Width),a.FullDim.BoxHeight=a.FullDim.Height/a.FullDim.Width*a.FullDim.BoxWidth,500<a.FullDim.BoxHeight&&(a.FullDim.BoxHeight=500,a.FullDim.BoxWidth=a.FullDim.BoxHeight/(a.FullDim.Height/a.FullDim.Width)),b.Slots[b.SlotIndex].List[b.Slots[b.SlotIndex].Index].ImageData=a),a=b.Slots[b.SlotIndex].List[b.Slots[b.SlotIndex].Index].ImageData);
b=a.FullDim.Width/a.FullDim.BoxWidth;if(1.1<=a.FullDim.Height/a.FullDim.BoxHeight||1.1<=b)return!0}return!1}function HasOpener(){var a=!1;if(window.opener)try{window.opener.cataloglite&&(a=!0)}catch(b){a=!1}return a}
function AddPartToCart(a,b,c,d,f,l,q,e,m,n,g,h){(new Image).src="/catalog/images/miatcc.jpg";var k=!1;if(window.opener){var p=!0;try{window.opener.cataloglite&&(p=!0)}catch(u){p=!1}if(p)if(window.opener.cataloglite)null!=mi_jsn?(p=window.opener.document.getElementById("addpart["+mi_jsn+"]"))?(p.click(),window.close()):k=!0:k=!0;else if(0<window.opener.document.getElementsByName("submitshowcart").length){for(var p=window.opener.document.getElementsByTagName("input"),r=null,t=0;t<p.length;++t)"hidden"==
p[t].type&&0==p[t].name.indexOf("partkey")&&p[t].value==b&&(r=p[t].name,r=r.replace("partkey[",""),r=r.replace("]",""));null!=r&&(p=window.opener.document.getElementsByName("addpart["+r+"]"),1==p.length&&p[0].click());window.close()}else k=!0;else k=!0}else k=!0;k&&("undefined"!=typeof h&&h?window.location=" /?tab=search&mfr="+RA.eURI(n)+"&partnum="+RA.eURI(g):cataloglite.Cart.AddPartToCartFromHeadLessMoreInfo(a,b,c,d,f,l,q,e,m,RedirectToCart))}var loadingPanel=null,loadingImage=new Image;
loadingImage.src="/jslib/rel_interstitial_loading.gif";function showLoading(){null===loadingPanel&&(loadingPanel=new YAHOO.widget.Panel("wait",{width:"240px",fixedcenter:!0,underlay:"shadow",close:!1,visible:!1,draggable:!1,modal:!0}),loadingPanel.setBody('<img src="/jslib/rel_interstitial_loading.gif"/>'));loadingPanel.setHeader("Loading");loadingPanel.render(document.body);loadingPanel.show()}function hideLoading(){null!==loadingPanel&&loadingPanel.hide()}
function RedirectToCart(a){showLoading();a="cart";if(window.opener)try{window.opener.cataloglite&&window.opener.__lang&&0<window.opener.__lang.length&&(a="/"+window.opener.__lang+"/cart/")}catch(b){}a+=GetSerializedCookieData("url","?");window.location=a};
