/*
 Copyright 2014 RockAuto, LLC
*/
String.prototype.trim=function(){return this.replace(/^\s\s*/,"").replace(/\s\s*$/,"")};$.ajaxSetup({cache:!1});var acmp_partcategory=0,last_text,user_input,help_cleared=!1,selectedRow=-1,selectedColumn=-1,highlightedRow=-1,highlightedColumn=-1,acmp_chosencarcode=0,acmp_textofchosencarcode="",keyboardInactivityTime=200,num_suggs=10;RA.IsMobileNew()&&(num_suggs=6);var max_input_length=255;$("html").mouseup(function(){clearSuggestions();$(".searchresultmsg").addClass("ra-hide")});
function getTbox(){var a=RA.ById("topsearchinput[input]");acmp_partcategory&&(a=RA.ById("navcarcodesearchinput["+currentSTCID+"]"));return a}var enoughTimeHasPassedSinceUserStoppedTyping=!1,keyboardInactivityTimer=null;function RestartKeyboardInactivityTimer(){keyboardInactivityTimer&&clearTimeout(keyboardInactivityTimer);keyboardInactivityTimer=setTimeout(function(){acmp_request()},keyboardInactivityTime)}
function acmp_keyup(a,c){var b;c&&(acmp_partcategory=1);window.event?b=a.keyCode:a.which&&(b=a.which);38!=b&&40!=b&&37!=b&&39!=b&&13!=b&&RestartKeyboardInactivityTimer()}
function acmp_request(){var a=getTbox().value;user_input=a;var c=a.substr(0,max_input_length);ctxPopup&&ctxPopup.hide();cataloglite.HideMobileWelcome();var b=cataloglite.Tab_GetActiveKey(),a=null;acmp_partcategory&&"extras"!=b&&(b=cataloglite.NavNode_GetData(currentSTCID))&&0<b.groupindex.length&&(a=b.carcode);if(0==$.trim(c).length)clearSuggestions();else{b={is_search:0};b.tab=cataloglite.Tab_GetActiveKey();var d=cataloglite.Tab_GetJSData(cataloglite.Tab_GetActiveKey());d&&"help"==d.tabtype&&(b.tab=
"help");c=c.toLowerCase();c=c.replace(/\s{2,}/g," ");c=c.replace(/^ /,"");b.text=c;0!=acmp_chosencarcode&&-1==c.indexOf(acmp_textofchosencarcode+" ")&&(acmp_chosencarcode=0,acmp_textofchosencarcode="");b.selectedcarcode=acmp_chosencarcode;null!=a?(b.carcode=a,b.currentSTCID=currentSTCID,cataloglite.CarPartTypeSuggest(b)):cataloglite.CatalogTopBarSuggest(b)}}var added_next_row_index=0,added_next_cell_index=0,added_clickable_cells=0;
function handleAutoCompleteResponse(a){clearSuggestions();selectedColumn=selectedRow=-1;added_clickable_cells=added_next_cell_index=added_next_row_index=0;var c=a.Suggestions;if(c){var b=num_suggs,d=0,e=!1;for(a=0;a<c.length;++a)"grid"==c[a].GridType&&(e=!0);for(a=0;a<c.length&&d<b;++a)e&&"GroupTitle"==c[a].Type||(0<c[a].Text.length&&addRowToTable(c[a],e).isGrid&&(b=c.length),"GroupTitle"!=c[a].Type&&++d,RA.IsMobileNew()&&25<b&&(b=25))}c=1;b=get_sug_el();for(a=0;a<b.rows.length;++a)b.rows[a].cells.length>
c&&(c=b.rows[a].cells.length);if(1<c)for(a=0;a<b.rows.length;++a)for(d=0;d<b.rows[a].cells.length;++d)b.rows[a].cells[d].style.width=100/c+"%",b.rows[a].cells[d].style.cursor="default",4==$(b.rows[a].cells[d]).text().length&&(b.rows[a].cells[d].style.textAlign="center");for(a=0;a<b.rows.length;++a)if(b.rows[a].cells.length<c)for(e=c-b.rows[a].cells.length,d=0;d<e;++d)b.rows[a].insertCell(b.rows[a].cells.length)}
var KEYCODE_UP=38,KEYCODE_DOWN=40,KEYCODE_LEFT=37,KEYCODE_RIGHT=39,KEYCODE_TAB=9,KEYCODE_SPACE=32,KEYCODE_ENTER=13,ignoreKey=!1,akhandler=function(a){if(a.preventDefault&&ignoreKey)a.preventDefault();else{if(a.keyCode==KEYCODE_UP||a.keyCode==KEYCODE_DOWN||a.keyCode==KEYCODE_LEFT||a.keyCode==KEYCODE_RIGHT||a.keyCode==KEYCODE_TAB){var c=this.selectionStart;this.selectionEnd=this.selectionStart=c;ignoreKey=!0;setTimeout(function(){ignoreKey=!1},1);a.keyCode==KEYCODE_UP||a.keyCode==KEYCODE_DOWN?(a.preventDefault&&
a.preventDefault(),scroll_sug(a)):a.keyCode==KEYCODE_LEFT||a.keyCode==KEYCODE_RIGHT?-1!=selectedRow&&(a.preventDefault&&a.preventDefault(),scroll_sug(a)):a.keyCode==KEYCODE_TAB&&-1!=selectedRow&&(a.preventDefault&&a.preventDefault(),c=getTbox(),selectRow(),clearSuggestions(),c.focus())}a.keyCode==KEYCODE_ENTER&&(a.preventDefault&&a.preventDefault(),-1!=selectedRow&&(c=getTbox(),selectRow(),clearSuggestions()),RA.ThrottleRepeats(function(){go_search()},"akhandler_go_search",1));"undefined"!==typeof myCarsPanel&&
null!=myCarsPanel&&myCarsPanel.hide()}};function bind_acmp_keydown_handler(a){a=RA.ById(a);a.addEventListener?a.addEventListener("keydown",akhandler,!1):a.attachEvent("onkeydown",akhandler)}
function bind_acmp_keyhandlers(){if(getTbox())if(getTbox().addEventListener){getTbox().addEventListener("keydown",akhandler,!1);for(var a=RA.GetJSDataFromHiddenInput("jstabkeys"),c=0;c<a.length;++c){var b=RA.ById("searchinput["+a[c]+"]");b&&b.addEventListener("keydown",akhandler,!1)}}else for(getTbox().attachEvent("onkeydown",akhandler),a=RA.GetJSDataFromHiddenInput("jstabkeys"),c=0;c<a.length;++c)(b=RA.ById("searchinput["+a[c]+"]"))&&b.attachEvent("onkeydown",akhandler)}
function go_search(a,c){if(window.simulate_old_html_catalog)return!1;ctxPopup&&ctxPopup.hide();if(a&&(acmp_partcategory=1,null==currentSTCID))return;1==get_sug_el().rows.length&&(selectedRow=0,selectRow());RA.IsMobileNew()&&getTbox().blur();var b=getTbox().value.substr(0,max_input_length);if(0==$.trim(b).length)clearSuggestions();else{var d=cataloglite.Tab_GetActiveKey(),e=null;acmp_partcategory&&"extras"!=d&&(d=cataloglite.NavNode_GetData(currentSTCID))&&0<d.groupindex.length&&(e=d.carcode);d={is_search:1};
d.tab=cataloglite.Tab_GetActiveKey();var f=cataloglite.Tab_GetJSData(cataloglite.Tab_GetActiveKey());f&&"help"==f.tabtype&&(d.tab="help");b=b.toLowerCase();b=b.replace(/\s{2,}/g," ");b=b.replace(/^ /,"");d.text=b;0!=acmp_chosencarcode&&-1==b.indexOf(acmp_textofchosencarcode+" ")&&(acmp_chosencarcode=0,acmp_textofchosencarcode="");d.selectedcarcode=acmp_chosencarcode;acmp_partcategory?(d.carcode=e,d.currentSTCID=currentSTCID,cataloglite.CarPartTypeSearch(d)):cataloglite.CatalogTopBarSearch(d)}}
function get_sug_el(){if(acmp_partcategory)return RA.ById("suggesttypescar["+currentSTCID+"]");cataloglite.Tab_GetActiveKey();return RA.ById("autosuggestions[topsearchinput]")}function reset_user_input(){getTbox().value=user_input}
function scroll_sug(a){var c=get_sug_el();if(a.keyCode==KEYCODE_DOWN)++selectedRow,-1==selectedColumn&&(selectedColumn=0),0<=selectedRow&&selectedRow<=c.rows.length-1&&0<c.rows[selectedRow].cells[selectedColumn].innerHTML.length?hiliteRow():(selectedRow=-1,hiliteRow(),reset_user_input());else if(a.keyCode==KEYCODE_UP)if(-1==selectedRow&&(selectedRow=c.rows.length),--selectedRow,-1==selectedColumn&&(selectedColumn=0),0<=selectedRow&&selectedRow<=c.rows.length-1){for(;0==c.rows[selectedRow].cells[selectedColumn].innerHTML.length&&
0<selectedRow;)--selectedRow;hiliteRow()}else selectedRow=-1,hiliteRow(),reset_user_input();if(a.keyCode==KEYCODE_LEFT){if(0<=selectedRow&&selectedRow<c.rows.length){--selectedColumn;if(0>selectedColumn)for(selectedColumn=c.rows[selectedRow].cells.length-1;0==c.rows[selectedRow].cells[selectedColumn].innerHTML.length&&0<selectedColumn;)--selectedColumn;hiliteRow()}}else a.keyCode==KEYCODE_RIGHT&&0<=selectedRow&&selectedRow<c.rows.length&&(++selectedColumn,selectedColumn>=c.rows[selectedRow].cells.length&&
(selectedColumn=0),0==c.rows[selectedRow].cells[selectedColumn].innerHTML.length&&(selectedColumn=0),hiliteRow());c.rows[selectedRow]&&c.rows[selectedRow].cells[selectedColumn]&&(c=c.rows[selectedRow].cells[selectedColumn].getAttribute("data-json"),0<c.length&&"GroupTitle"==RA.json_decode(c).Type&&scroll_sug(a))}var mouseOverFillsInText=!1;
function addRowToTable(a,c){var b=a.Text,d=get_sug_el(),e=b,f=!1;a.SelectedValue&&(e=a.SelectedValue);a.GridType&&"grid"==a.GridType&&(f=!0);d.style.display="";var h=-1,g=-1,l=null;added_clickable_cells<num_suggs?(h=d.rows.length,l=d.insertRow(h)):(added_next_row_index==num_suggs&&(added_next_row_index=0),h=added_next_row_index,l=d.rows[added_next_row_index]);++added_next_row_index;"GroupTitle"!=a.Type&&++added_clickable_cells;g=l.cells.length;d=l.insertCell(g);RA.IsMobileNew()&&"GroupTitle"!=a.Type&&
"Help"!=a.Type&&(d.innerHTML+='<img src="/Images/mobile/acmp_fill_arrow_blue.png" class="acmp-fill-arrow" style="'+(c?"font-size: .75em; ":"")+'" onmouseup="RA.StopBubble(event); fillSuggestionTextBox(getTbox(), \''+RA.html_special_chars(e)+"' + ' '); acmp_request(); getTbox().focus(); return false;\">");d.innerHTML+=b;d.setAttribute("data-f",e);d.setAttribute("data-json",RA.json_encode(a));$(d).addClass(".no-text-select");"GroupTitle"==a.Type?$(d).addClass("acmp-cell-title"):$(d).addClass("acmp-cell");
c&&RA.IsMobileNew()&&$(d).css("max-width","7em");RA.IsMobileNew()||(l.cells[g].onmouseover=function(){"GroupTitle"!=a.Type&&($(this).addClass("hlt"),highlightedRow=h,highlightedColumn=g,mouseOverFillsInText?(selectedRow=h,selectedColumn=g,hiliteRow()):hiliteRowMouse())});l.cells[g].onmouseout=function(){"GroupTitle"!=a.Type&&(highlightedColumn=highlightedRow=-1,mouseOverFillsInText&&(selectedColumn=selectedRow=-1,reset_user_input()),$(this).removeClass("hlt"))};l.cells[g].onmouseup=function(){if("GroupTitle"!=
a.Type)if(clearSuggestions(),clearSearches(),"Car"==a.Type){var b=null;a.Year&&(null==b||a.Year<b)&&(b=a.Year);if(a.YearList&&0<a.YearList.length){for(var c=UnpackIncrementallyEncodedWordList(a.YearList.split(",")),d={},e=0;e<c.length;++e){var f={};f[a.Model]={};d[c[e]]={models:f};if(null==b||c[e]<b)b=c[e]}cataloglite.TemporaryChildSearchProgression[RA.ToLower("catalog-"+a.Make)]={children:d}}var g={};if(a.VehicleClass){c=cataloglite.GetCheckedMarketFlags();d=a.VehicleClass.split(",");f=!1;for(e=
0;e<d.length;++e)c[d[e]]&&(f=!0);if(!f)for(e=0;e<d.length;++e)g[d[e]]=d[e]}a.CarCode&&0<a.CarCode.length&&(acmp_chosencarcode=a.CarCode,acmp_textofchosencarcode=a.Year+" "+a.Make+" "+a.Model+" "+a.Engine);e=getTbox().value;" "!=e[e.length-1]&&(getTbox().value+=" ");cataloglite.SearchToRemember.SelectedSuggestion=a;e={steps:{}};e.steps.tab="catalog";e.steps.make=a.Make;e.steps.year=a.Year;e.steps.model=a.Model;e.steps.carcode=a.CarCode;e.steps.groupname=a.GroupName;e.steps.parttype=a.PartType;e.dont_change_url_until_end=
!0;e.ok_to_expand_single_child_node=!0;RA.SubscribeOnce("jstab["+e.steps.tab+"]","expand_complete",function(){cataloglite.CheckMinRequiredYearCheckBox(b);cataloglite.CheckFirstRequiredMarketFlag(g)});cataloglite.InCatalogApp()?cataloglite.AutoOpen(e):cataloglite.PostAutoOpen(e)}else"Extras"==a.Type?(e={steps:{}},e.steps.tab="extras",e.steps.groupname=a.GroupName,e.steps.subgroupname=a.SubGroupName,e.steps.parttype=a.PartType,e.dont_change_url_until_end=!0,cataloglite.InCatalogApp()?cataloglite.AutoOpen(e):
cataloglite.PostAutoOpen(e)):"Help"==a.Type&&(e=a.HelpURL,cataloglite.InHelpApp()?cataloglite.Tab_GetJSData(cataloglite.Tab_GetActiveKey()).pageid==a.HPageID?cataloglite.JumpToAnchorDontChangeURL(a.HAnchor):window.location.href="/help/?page="+RA.eURI(a.HPageID)+"&qsearch="+RA.eURI(getTbox().value)+"#"+a.HAnchor:FAQpopup(e,null,null,getTbox()))};b=[];f&&(b.isGrid=!0);return b}function array_flip(a){var c,b={};for(c in a)a.hasOwnProperty(c)&&(b[a[c]]=c);return b}
function removeEachWord(a,c){for(var b=c.split(" "),d=0;d<b.length;++d)a=a.replace(b[d],"");return a}function isset(a){return"undefined"!==typeof a&&null!=a}
function selectRow(){var a=get_sug_el();if(a&&selectedRow<a.rows.length&&0<=selectedRow&&0<=selectedColumn&&selectedColumn<a.rows[selectedRow].cells.length){var c=getTbox(),b=a.rows[selectedRow].cells[selectedColumn].getAttribute("data-json"),b=RA.json_decode(b);"Help"!=b.Type&&"GroupTitle"!=b.Type&&(b=a.rows[selectedRow].cells[selectedColumn].getAttribute("data-f"),b=b.replace(/<[^>]+>/gi,""),b=b.replace(/\s\s+/gi," "),b=b.replace(/&amp;/gi,"&"),c.value=b+" ");a.rows[selectedRow].cells[selectedColumn].onmouseup()}}
function hiliteRow(){for(var a=get_sug_el(),c=0;c<a.rows.length;++c)for(var b=0;b<a.rows[c].cells.length;++b)$(a.rows[c].cells[b]).removeClass("hlt");c=getTbox();a&&selectedRow<a.rows.length&&0<=selectedRow&&0<=selectedColumn&&selectedColumn<a.rows[selectedRow].cells.length&&(b=a.rows[selectedRow].cells[selectedColumn].getAttribute("data-json"),b=RA.json_decode(b),"0"!=b.CarCode&&(acmp_chosencarcode=b.CarCode,acmp_textofchosencarcode=b.Year+" "+b.Make+" "+b.Model+" "+b.Engine),"Help"!=b.Type&&"GroupTitle"!=
b.Type&&(b=a.rows[selectedRow].cells[selectedColumn].getAttribute("data-f"),fillSuggestionTextBox(c,b)),$(a.rows[selectedRow].cells[selectedColumn]).addClass("hlt"))}function fillSuggestionTextBox(a,c){c=c.replace(/<[^>]+>/gi,"");c=c.replace(/  /gi," ");c=c.replace(/&amp;/gi,"&");a.value=c}
function hiliteRowMouse(){for(var a=get_sug_el(),c=0;c<a.rows.length;++c)for(var b=0;b<a.rows[c].cells.length;++b)$(a.rows[c].cells[b]).removeClass("hlt");a&&highlightedRow<a.rows.length&&0<=highlightedRow&&0<=highlightedColumn&&highlightedColumn<a.rows[highlightedRow].cells.length&&$(a.rows[highlightedRow].cells[highlightedColumn]).addClass("hlt")}function clearSuggestions(){var a=get_sug_el();if(null!=a){for(;a.hasChildNodes();)a.removeChild(a.firstChild);a.style.display="none"}selectedRow=-1}
function clearSearches(a){$(".hlsearch").removeClass("hlsearch");$(".searchresultmsg").html("");cataloglite.TemporaryChildSearchProgression={}}function escapeRegExp(a){return a.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")}function fTrunc(a,c){return Math.floor(a*Math.pow(10,c))/Math.pow(10,c)}
function UnpackIncrementallyEncodedWordList(a){for(var c=[],b="",d=0;d<a.length;++d){var e,f;f=a[d].split(" ");2==f.length?(e=f[0],f=f[1]):(e=a[d].charAt(0),f=a[d].substring(1));b=b.substring(0,e)+""+f;c[c.length]=b}return c}
function CalculateNGramUnionIntersectionLive(a,c,b){var d={u:0,i:0};if(c.length<a.length){var e=a;a=c;c=e}if(0==a.length||a.length<b||0==c.length||c.length<b)return d;var e=a.length-(b-1),f=c.length-(b-1);if(a==c)return d.u=e+f,d.i=e,d;for(var h=Array(f),g=0;g<f;++g)h[g]=!1;for(var l=e+f,m=0,n,k,g=0;g<e;++g){n=a.substring(g,g+b);for(k=0;-1!=(k=c.indexOf(n,k))&&k<f&&1==h[k];)k+=1;k<f&&-1!=k&&0==h[k]&&(h[k]=!0,++m)}d.u=l;d.i=m;return d}
function CalculateSimilarityScore(a,c){var b=0,d=0;if(c.length<a.length){var e=a;a=c;c=e}e=CalculateNGramUnionIntersectionLive(a,c,1);b+=e.u;d+=e.i;e=CalculateNGramUnionIntersectionLive(a,c,2);b+=e.u;d+=e.i;8<=a.length&&(e=CalculateNGramUnionIntersectionLive(a,c,3),b+=e.u,d+=e.i);2<=a.length&&2<=c.length&&(b+=2,a.charAt(0)==c.charAt(0)&&a.charAt(a.length-1)==c.charAt(c.length-1)&&(d+=1));return 0<b?2*d/b:0}
function Levenshtein(a,c){if(0==a.length)return c.length;if(0==c.length)return a.length;var b=[],d;for(d=0;d<=c.length;++d)b[d]=[d];var e;for(e=0;e<=a.length;++e)b[0][e]=e;for(d=1;d<=c.length;++d)for(e=1;e<=a.length;++e)c.charAt(d-1)==a.charAt(e-1)?b[d][e]=b[d-1][e-1]:b[d][e]=Math.min(b[d-1][e-1]+1,Math.min(b[d][e-1]+1,b[d-1][e]+1));return b[c.length][a.length]};
